[build]
  command = "npm run build"
  publish = "dist"

# Ensure correct MIME types and single page app fallback
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
